backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "assets/img/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/blog_post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
